### ISSUE TITLE
repr: remove these parentheses

### ISSUE THREAD

**Issue by nazar-pc** [dtolnay/enumn#1]
HI, by specifying `#[repr(u16)]` on enum compiler complains like this:
```
142 | #[repr(u16)]
    |       ^^^^^ help: remove these parentheses
```
This is clearly something within code generated by the macro, can you take a look why this happens?

**Comment by dtolnay** [comment]
Thanks! This is a new warning added to a recent rustc. I've published enumn 0.1.2 with the fix.
